server.port: 8080


spring:
    data:
        elasticsearch:
            cluster-name: elasticsearch #es集群的名称
            cluster-nodes: 127.0.0.1:9300 #es的连接地址及端口号
            repositories:
                enabled: true